# fly.toml app configuration file generated for twilio on 2023-06-30T22:59:24+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "twilio"
primary_region = "ams"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
